"""Solutions content -- sab kuch "Zentallio_Iris_Rule_Book_Complete.pdf" se.

tools/build_solutions.py isay parh kar /solutions aur /solutions/<product>
(desktop + m/ mobile) pages banata hai. Content badalna ho to sirf yahan badlo,
phir:  python3 tools/build_solutions.py
"""

# ---------------------------------------------------------------- platform
PLATFORM = {
    'who': "Zentallio is the AI Decision Platform for Food & Beverage and Fashion Retail. "
           "Its agent, Iris, reads every signal — demand, cost, sell-through, service — "
           "and turns it into the next move.",
    'tagline': 'AI-driven retail, from signal to decision.',
    'iris': "Iris is the AI that narrates every screen, flags what needs a human and acts "
            "on the rest once approved. It names the cause, costs the move and proposes the action.",
    'spine': "One data spine from the till to the ledger. Operators configure a sector "
             "playbook, not a custom project: live in weeks, learning from day one.",
    'layers': [
        ('L1', 'Zen Rules', 'Deterministic thresholds that fire on the shift the breach happens — no model lag, no waiting for a report.'),
        ('L2', 'Zen Models', 'Forecasting and ML models that predict early enough to act on, with the cause named and the move costed.'),
        ('L3', 'Ask Iris', 'Conversational layer: you ask what moved and why, and Iris answers with the recommended action for a human to approve.'),
    ],
    'numbers': [('10', 'F&B sectors'), ('149', 'F&B AI solutions'), ('9', 'Fashion sectors'),
                ('55+12', 'Fashion solutions + core POS'), ('6', 'Live products'), ('6', 'Regions')],
    'book': 'Configured demo in 3–5 working days · no hardware · no long-term contract',
    'fb_caveat': 'Modelled from pilot assumptions and comparable F&B benchmarks — not yet a deployed-client result. Zentallio will publish real numbers as founding pilots conclude.',
    'demo_caveat': 'Illustrative data from the website demo — not a client result.',
}

# ---------------------------------------------------------------- products
# img: solutions/li_<slug>.png (agar folder mein ho to poster + icon wahi se banta hai)
PRODUCTS = [
    {
        'slug': 'balanced-scorecard', 'name': 'Balanced Scorecard', 'role': 'Executive board',
        'mono': 'BS', 'label': 'Finance · L2 · four lenses, live', 'app': 'scorecard', 'hue': '#ff2d95',
        'line': 'Four perspectives — financial, customer, process, learning — on one live board.',
        'what': 'The executive board: Financial, Customer, Operational and AI-Learning lenses, each with its '
                'L1 rule thresholds, L2 model accuracies and an Ask Iris explanation of what moved and what to do.',
        'pillars': [
            ('Financial lens', 'Margin, cost and sell-through against the thresholds you set — season-to-date, live.'),
            ('Customer lens', 'Repeat rate, member mix and returning clients, scored on the same board.'),
            ('Operational lens', 'Readiness, on-time handover, size-run completeness — the floor in one row.'),
            ('AI-Learning lens', 'Every L2 model shown with its accuracy, so you see how far to trust the forecast.'),
        ],
        'outcomes': [('+2.1 pt', 'net margin', 'Casual Dining'), ('3 days', 'month-end close', 'Quick Service'),
                     ('+15%', 'contract renewals', 'Institutional & B2B'), ('+11%', 'per-cover revenue', 'Fine Dining')],
        'kw': [],  # scorecard har sector ka board hai -- keyword list ki zarurat nahi
    },
    {
        'slug': 'point-of-sale', 'name': 'Point of Sale', 'role': 'Live till',
        'mono': 'POS', 'label': 'Live till · Iris upsell', 'app': 'pos', 'hue': '#15F2F2',
        'line': 'Every station on one order spine, with Iris suggesting the upsell at the moment of sale.',
        'what': 'The till: counter, tables, drive-thru, kitchen, dispatch, delivery and feedback on one order spine, '
                'with Iris suggesting the upsell at the moment of sale.',
        'pillars': [
            ('One order spine', 'Counter, tables, drive-thru, kitchen, dispatch, delivery and feedback read the same order.'),
            ('Iris upsell', 'The suggestion lands while the guest is still at the till — not in next month’s report.'),
            ('Every channel', 'Kiosk, app, web and aggregators on one menu: an item goes 86 and disappears everywhere.'),
            ('12 core POS', 'Checkout, returns, tender, tax, loyalty, offline resilience — standard in every Fashion sector.'),
        ],
        'spine': ['Counter', 'Tables', 'Drive-thru', 'Kitchen', 'Dispatch', 'Delivery', 'Feedback'],
        'outcomes': [('+18%', 'attach rate from Iris upsell', 'Café & Bakery'), ('−41s', 'average counter-to-hand time', 'Quick Service'),
                     ('−34s', 'average queue wait', 'Café & Bakery'), ('+12%', 'peak-hour throughput', 'Quick Service')],
        'kw': ['kiosk', 'drive-through', 'combo', 'modifier', 'split bill', 'open tab', 'tip handling', 'omni-channel',
               'checkout', 'upsell', 'suggestion', 'bar workflow', 'drink builder', 'weight', 'scoop', 'voucher',
               'ticket', 'offline', 'age verification', 'bowl', 'table management', 'kds', 'kitchen display',
               'pre-order', 'bulk orders', 'add-on', 'customer capture', 'loyalty', 'store credit', 'returns',
               'tender', 'appointment', 'fit guidance', 'gifting', 'order routing'],
    },
    {
        'slug': 'numerus', 'name': 'Numerus', 'role': 'CFO',
        'mono': 'NC', 'label': 'Balanced ledger · balanced, not estimated', 'app': 'numerus', 'hue': '#E0B872', 'src': 'li_numerus-cfo.png',
        'line': 'The CFO’s ledger — balanced, not estimated.',
        'what': 'Finance: executive cockpit, financial reporting and approvals in one ledger.',
        'pillars': [
            ('Executive cockpit', 'The numbers the CFO signs, live — not rebuilt from spreadsheets at month end.'),
            ('Financial reporting', 'Per-brand, per-site and consolidated P&L from the same entries the till wrote.'),
            ('Approvals', 'Every move Iris recommends lands as an approval — a human signs before money moves.'),
            ('One ledger', 'Commission, settlement, deposits and rebates reconciled to the order that caused them.'),
        ],
        'outcomes': [('3 days', 'month-end close', 'Quick Service'), ('3 days', 'consolidated close', 'Institutional & B2B'),
                     ('−19%', 'aggregator commission leakage', 'Cloud Kitchen'), ('−18%', 'comp & void leakage', 'Casual Dining')],
        'kw': ['invoic', 'billing', 'settlement', 'p&l', 'contribution', 'margin', 'costing', 'pour cost', 'revenue',
               'service charge', 'split bill', 'deposit', 'rebate', 'commission', 'voucher', 'subsidy', 'pricing',
               'markdown', 'reporting', 'reconciliation', 'cash management', 'shift close', 'audit trail', 'tax',
               'discount governance', 'comps', 'unit economics', 'concession', 'price parity'],
    },
    {
        'slug': 'nexus', 'name': 'Nexus', 'role': 'Supply Chain',
        'mono': 'NX', 'label': 'Forecast, procurement, logistics', 'app': 'nexus', 'hue': '#7FD8F0',
        'line': 'Demand forecast, procurement and logistics tied to what actually sold.',
        'what': 'Supply chain: demand forecast, procurement and logistics tied to what actually sold.',
        'pillars': [
            ('Demand forecast', 'Built from what actually sold — not from what was ordered last month.'),
            ('Procurement', 'Reorders sized against the forecast and pulled forward before a date that cannot move.'),
            ('Logistics', 'Stock routed to the door, counter or kitchen that clears it — before anyone notices it’s stuck.'),
            ('Shrink & waste', 'Depletion at recipe, batch and lot level, so variance is caught the shift it happens.'),
        ],
        'outcomes': [('1.8%', 'food waste (was 4.1%)', 'Quick Service'), ('1.9%', 'display-case waste (was 3.4%)', 'Café & Bakery'),
                     ('−28%', 'freezer shrink', 'Ice Cream & Desserts'), ('0', 'stock-out Sundays', 'Ice Cream & Desserts')],
        'kw': ['inventory', 'stock', 'depletion', 'forecast', 'demand', 'procurement', 'supplier', 'sourcing',
               'replenish', 'allocation', 'fifo', 'waste', 'production', 'batch', 'display case', 'transfer',
               'drop', 'sell-through', 'size-curve', 'size-run', 'shade-curve', 'colourway', 'clearance', 'yield',
               'headcount', 'central kitchen', 'keg', 'cold-chain', 'packaging', 'lot', 'prep', 'locator',
               'mix control', 're-order', 'replenishment'],
    },
    {
        'slug': 'motus', 'name': 'Motus', 'role': 'Operations',
        'mono': 'MO', 'label': 'Standards, assets, energy', 'app': 'motus', 'hue': '#5CE1B5',
        'line': 'Standards, assets and energy — across every site.',
        'what': 'Operations: standards, assets and energy across every site.',
        'pillars': [
            ('Standards', 'One standard across every site — allergens, food safety and compliance enforced, not hoped for.'),
            ('Assets', 'Freezers, machines and kitchen stations read live, with Iris flagging drift before it fails.'),
            ('Energy', 'Every site’s running cost on the same board as its sales.'),
            ('Audit-ready', 'Food-safety and compliance evidence produced on request — the audit as an operating condition.'),
        ],
        'outcomes': [('100%', 'allergen label accuracy', 'Health & Wellness'), ('100%', 'age-gate compliance', 'Beverages & Drinks'),
                     ('−31%', 'syrup overuse', 'Beverages & Drinks'), ('1', 'system across every pop-up', 'Niche & Experience')],
        'kw': ['safety', 'temperature', 'compliance', 'standards', 'machine', 'haccp', 'allergen', 'traceab',
               'audit', 'cold-chain', 'multi-site', 'rollout', 'offline', 'kitchen display', 'kds', 'station',
               'labelling', 'responsible', 'age verification', 'integration hub', 'daypart', 'out of stock',
               'recall', 'expiry', 'dye-lot', 'shade continuity', 'menu auto-switch', 'menu lockout',
               'extended hours', 'mobile, festival', 'nutrition', 'macro', 'spillage', 'tester'],
    },
    {
        'slug': 'manus', 'name': 'Manus', 'role': 'Workforce',
        'mono': 'MA', 'label': 'Roster, payroll, compliance', 'app': 'manus', 'hue': '#C4A8FF',
        'line': 'Rostering from forecast; overtime, absence and compliance handled before payroll.',
        'what': 'Workforce: rostering from forecast; overtime, absence and compliance handled before payroll.',
        'pillars': [
            ('Roster from forecast', 'People scheduled against the demand curve — not against habit.'),
            ('Overtime & absence', 'Caught on the shift it happens, before it reaches payroll.'),
            ('Compliance', 'Rest, hours and certification rules checked before the roster is published.'),
            ('Capacity by skill', 'Work loaded by skill and stage — atelier, fitters, sections — so capacity is a number.'),
        ],
        'outcomes': [('+12%', 'peak-hour throughput', 'Quick Service'), ('+0.6', 'table turns per service', 'Casual Dining'),
                     ('+31%', 'orders per kitchen hour', 'Cloud Kitchen'), ('96%', 'course pacing on time', 'Fine Dining')],
        'kw': ['staffing', 'server', 'section', 'capacity', 'karigar', 'fitting & installation', 'appointment',
               'consultation', 'cutting-table', 'productivity', 'shift close', 'pacing', 'coursing', 'table turn',
               'queue', 'peak', 'speed of service', 'run sheet', 'experience design', '24-hour', 'rider handover',
               'fast bar workflow'],
    },
]


# ---------------------------------------------------------------- F&B sectors
def G(title, sub, items):
    return {'title': title, 'sub': sub, 'items': items}

CTR = ('At the counter', 'Where the order is taken, and made.')
CTR2 = ('At the counter (continued)', 'And the rest of the counter.')
GST = ('The guest', 'The guest, remembered.')
GST2 = ('The guest (continued)', 'And the rest of the guest journey.')
KIT = ('Kitchen & stock', 'What you make. What it costs. What you lose.')
KIT2 = ('Kitchen & stock (continued)', 'And the rest of the kitchen.')
KITC = ('Kitchen & stock (compliance)', 'The kitchen, accounted for.')
PLT = ('The platform', 'The platform underneath.')
PLT2 = ('The platform (continued)', 'And the rest of the platform.')

FB = [
    {
        'id': 'qsr', 'code': 'FB-01', 'num': '01', 'name': 'Quick Service & Street Food', 'short': 'Quick Service',
        'hue': '#E5A24B', 'link': '/food/solutions/quick-service-street-food', 'formats': 8, 'count': 13,
        'headline': 'The AI that runs the rush, the drive-through, every channel.', 'brand': 'Croq Express', 'stack': 'quick-service stack',
        'promises': ['Kiosk, drive-through, counter and every aggregator on one order book — sequenced by promise time, not by whoever shouted loudest.',
                     'Lane depth, order-to-window time and the second window measured to the second — because in QSR the queue is the P&L.',
                     'One menu across kiosk, app, web and five aggregators. An item goes 86 at the counter and disappears everywhere in the same second.'],
        'kpis': [('Orders / hr', '412'), ('Order to window', '96s'), ('Food cost', '30.8%')],
        'board': 'The whole rush on one board. Drive-through times, kiosk mix, food cost and forecast accuracy — live, with Iris naming the item that quietly moved your margin.',
        'story_t': 'Sixty seconds decides everything.',
        'story': ['In quick service, the margin lives in the rush: a lane that stalls, a fryer that runs ahead of demand, a promo that leaks — each costs more than a bad month of rent. Most operators only find out after close.',
                  'Zentallio runs the counter minute by minute: the Drive-Through watches every car, KDS routes each item to the right station, recipe-level depletion catches shrink the moment it happens, and the Staffing AI schedules people against the demand curve — not against habit.'],
        'outcomes': [('−41s', 'average counter-to-hand time'), ('+12%', 'peak-hour throughput'), ('1.8%', 'food waste (was 4.1%)'), ('3 days', 'month-end close')],
        'groups': [
            G(*CTR, [('Kitchen Display & Station Routing', 'Queue ML'), ('Self-Service Kiosk', 'Recommendation'), ('Drive-Through Management', 'Queue ML'), ('Daypart Menu Auto-Switch', 'L1 Zen Rules')]),
            G(*CTR2, [('Combo & Modifier Engine', 'Recommendation'), ('Hourly Sales Heatmap & Staffing AI', 'Forecast'), ('Loyalty, App & Offer Engine', 'Recommendation'), ('Recipe-Based Inventory Depletion', 'Anomaly Detection')]),
            G(*PLT, [('Real-Time Out of Stock', 'L1 Zen Rules'), ('Delivery Aggregator Sync', 'L1 Zen Rules'), ('Speed of Service Analytics', 'Queue ML'), ('Food Safety & Temperature Compliance', 'IoT'), ('Multi-Site Rollout & Standards', 'L1 Zen Rules')]),
        ],
    },
    {
        'id': 'casual', 'code': 'FB-02', 'num': '02', 'name': 'Casual Dining', 'short': 'Casual Dining',
        'hue': '#FF8A5C', 'link': '/food/solutions/casual-dining', 'formats': 8, 'count': 17,
        'headline': 'The AI that runs the floor, the turn, every course.', 'brand': 'Brasserie Croq', 'stack': 'casual stack',
        'promises': ['Tables, courses, servers and every split bill reconciled.',
                     'Table turn time is the number that decides a Saturday. Iris seats, fires and paces against it rather than hoping.',
                     'Starters, mains and desserts fired to arrive together for the table — not for the ticket.'],
        'kpis': [('Covers / night', '284'), ('Table turn', '68m'), ('Course accuracy', '97.2%')],
        'board': 'The whole floor on one board. Covers, turn time, comps and course accuracy — live, with Iris naming the section where the evening actually slipped.',
        'story_t': 'Full tables are a system, not luck.',
        'story': ['Casual dining wins on turns and dies on friction: slow coursing, split-bill chaos, comps nobody can explain. The dining room generates a thousand signals a night — and most of them are lost by morning.',
                  'Zentallio keeps the floor moving: table-turn prediction paces seating, coursing runs itself, every comp and void is attributed, and Iris tells the manager which section is drifting before the guests feel it.'],
        'outcomes': [('+0.6', 'table turns per service'), ('+9%', 'covers per night'), ('−18%', 'comp & void leakage'), ('+2.1 pt', 'net margin')],
        'groups': [
            G(*CTR, [('Table Management & Floor Plan', 'Regression'), ('Server Assignment & Multi-Course Coursing', 'Scoring'), ('Split Bill', 'Rule Engine'), ('Open Tab Management', 'Rule Engine')]),
            G(*CTR2, [('Tip Handling & Service Charge', 'Scoring'), ('Dietary Preference Profiling AI', 'Recommendation'), ('KDS', 'Forecast'), ('Table Turn & Pacing Intelligence', 'Forecast')]),
            G(*GST, [('Reservation & Waitlist Management', 'Classifier'), ('Waitlist, Reservations & No-Show Prediction', 'Classifier'), ('Loyalty, CRM & Guest Recognition', 'Recommendation'), ('Omni-Channel Ordering', 'Queue ML')]),
            G(*KIT, [('Menu Engineering & Course Mix', 'Cost ML'), ('Recipe Costing & Portion Control', 'Cost ML'), ('Waste, Comps & Void Control', 'Anomaly Detection'), ('Server Performance & Section Balance', 'Segmentation'), ('Integration Hub', 'L1 Zen Rules')]),
        ],
    },
    {
        'id': 'fine', 'code': 'FB-03', 'num': '03', 'name': 'Fine Dining & Premium', 'short': 'Fine Dining',
        'hue': '#D8B65C', 'link': '/food/solutions/fine-dining-premium', 'formats': 4, 'count': 8,
        'headline': 'The AI that runs your dining room, every cover, the cellar.', 'brand': 'Maison Lumière', 'stack': 'fine-dining stack',
        'promises': ['Service at the pass, a cellar that depletes as it pours, and menu engineering that protects the margin on every cover.',
                     'Covers paced to the kitchen’s real capacity, allergens flagged before the plate leaves the pass, and each seating costed while it is still seated.',
                     'Every pour depletes the bin, every vintage re-costs as the list moves, and the wine margin holds at 71% without touching a single price.'],
        'kpis': [('Covers', '184 / 210'), ('Pass time', '11m 40s'), ('Cellar margin', '71.4%')],
        'board': 'The whole service on one board. Covers, guest recognition, wine margin and pass timing — live, with Iris naming the detail that separated a good night from an exceptional one.',
        'story_t': 'Service as choreography, margin as craft.',
        'story': ['At the premium end, one mistimed course or one forgotten preference undoes months of reputation. Excellence at this level is memory plus timing — at a scale no brigade can hold in its head.',
                  'Zentallio remembers for you: guests by name and preference, tasting menus paced to the minute, wine paired by margin as well as palate, every cover measured — so the room performs like the tasting menu was written for each table.'],
        'outcomes': [('+18%', 'wine attach on pairings'), ('96%', 'course pacing on time'), ('+11%', 'per-cover revenue'), ('2×', 'repeat VIP visits')],
        'groups': [
            G(*CTR, [('Tasting Menu Coursing & Pacing', 'Regression'), ('Wine & Beverage Pairing Module', 'Recommendation'), ('High-AOV Upsell AI', 'Recommendation'), ('Per-Cover Revenue Tracker', 'Attribution')]),
            G(*CTR2, [('Chef’s Table Pre-Order Manager', 'Rule Engine'), ('Table Turn Predictor AI', 'Regression'), ('Reservation & Deposit Management', 'Classifier'), ('Clienteling', 'Classifier')]),
        ],
    },
    {
        'id': 'cafe', 'code': 'FB-04', 'num': '04', 'name': 'Café, Coffee & Bakery', 'short': 'Café & Bakery',
        'hue': '#C9A27C', 'link': '/food/solutions/cafe-coffee-bakery', 'formats': 9, 'count': 17,
        'headline': 'The AI that runs the bar, the bake, the last hour.', 'brand': 'Donna’s', 'stack': 'café stack',
        'promises': ['Label at the bar, modifiers that hold, a display case that counts itself down.',
                     'Yield, recipe cost and tomorrow’s production plan built from what actually sold, not from what was baked last Tuesday.',
                     'Markdown timed by remaining shelf life rather than the clock — because going earlier beats going deeper.'],
        'kpis': [('Drinks / hr', '168'), ('Case sell-through', '94.2%'), ('Waste', '2.6%')],
        'board': 'The bar and the bake on one board. Drinks per hour, case sell-through, waste and margin — live, with Iris naming the item that quietly stopped paying.',
        'story_t': 'The morning rush, already counted.',
        'story': ['A café earns its week before 11am — and loses it in a display case. Croissants baked on instinct, milk steamed into queues that were never forecast, yesterday’s bake quietly binned. The busiest format in F&B is also the most guessed-at.',
                  'Zentallio removes the guessing: the bar flows at barista speed, the display case depletes unit by unit as the till sells, production limits follow the forecast, and end-of-day markdowns fire before anything reaches the bin.'],
        'outcomes': [('−34s', 'average queue wait'), ('+18%', 'attach rate from Iris upsell'), ('1.9%', 'display-case waste (was 3.4%)'), ('3 days', 'books closed monthly')],
        'groups': [
            G(*CTR, [('Fast Bar Workflow & Barista Label Printing', 'Queue ML'), ('Modifier Engine', 'Clustering'), ('Weight-Based Selling', 'Forecast'), ('Personalised Order Suggestions AI', 'Recommendation')]),
            G(*GST, [('Loyalty & Rewards Engine', 'Recommendation'), ('RFM Customer Intelligence', 'Segmentation ML'), ('Voucher & Promo Redemption', 'Anomaly Detection'), ('Omni-Channel Ordering', 'Queue ML')]),
            G(*GST2, [('Social Selling Agent', 'LLM Agent'), ('Customer Feedback & NPS', 'Sentiment ML'), ('Daily Production Limits', 'Forecast'), ('Display Case Inventory', 'Forecast')]),
            G(*KIT, [('End-of-Day Markdown AI', 'Dynamic Pricing'), ('Recipe & BOM Intelligence', 'Cost ML'), ('Live Ingredient Ledger & Auto-Depletion', 'Anomaly Detection'), ('Waste & Production Variance', 'Anomaly Detection'), ('Integration Hub', 'L1 Zen Rules')]),
        ],
    },
    {
        'id': 'dessert', 'code': 'FB-05', 'num': '05', 'name': 'Ice Cream, Desserts & Sweets', 'short': 'Ice Cream & Desserts',
        'hue': '#5CD9FF', 'link': '/food/solutions/ice-cream-desserts-sweets', 'formats': 6, 'count': 12,
        'headline': 'The AI that runs the scoop, the freezer, peak hour.', 'brand': 'Croq Glacé', 'stack': 'dessert stack',
        'promises': ['Weighed and scooped billing, a topping engine that prices every mix-in, and a display freezer that counts itself down.',
                     'Every tub tracked by batch and best-before, hardening times respected, and Iris flagging the flavour that will not survive the weekend.',
                     'Saturday at eight is a different business from Tuesday at three. Production, staffing and the menu all move with the queue, not against it.'],
        'kpis': [('Scoops today', '1,840'), ('Average ticket', '$6.40'), ('Waste', '1.9%')],
        'board': 'Every gram on one board. Scoop yield, freezer shrink, batch cost and weekend demand — live, with Iris naming where the margin melted.',
        'story_t': 'Sweetness, measured to the gram.',
        'story': ['Dessert margins melt fast — literally. Freezer shrink, over-scooping, weekend batches sized by memory: gram-level products with guess-level control.',
                  'Zentallio weighs everything: scoop and gram billing at the till, freezer inventory live, batch production tuned to the weekend curve, and pricing that knows what a topping actually costs.'],
        'outcomes': [('−28%', 'freezer shrink'), ('+14%', 'gram-level margin accuracy'), ('+22%', 'weekend batch fill'), ('0', 'stock-out Sundays')],
        'groups': [
            G(*CTR, [('Topping & Mix-In Modifier Engine', 'Recommendation'), ('Seasonal & Limited-Time Menu', 'Forecast'), ('Customer Favourite Recall AI', 'Memory'), ('Queue & Peak-Hour Flow', 'Queue ML')]),
            G(*KIT, [('Delivery & Cold-Chain Integrity', 'Forecast'), ('Loyalty, Streaks & Family Wallets', 'Recommendation'), ('Display Freezer Inventory', 'Anomaly Detection'), ('Gifting, Packaging & Take-Home', 'Recommendation')]),
            G(*KIT2, [('End-of-Day Markdown AI', 'Forecast'), ('Waste Minimiser AI', 'Forecast'), ('Machine & Batch Freezer Monitoring', 'IoT'), ('Weight & Scoop-Based Billing', 'L1 Zen Rules')]),
        ],
    },
    {
        'id': 'beverage', 'code': 'FB-06', 'num': '06', 'name': 'Beverages & Drinks', 'short': 'Beverages & Drinks',
        'hue': '#A8E05F', 'link': '/food/solutions/beverages-drinks', 'formats': 9, 'count': 17,
        'headline': 'The AI that runs the bar, the pour, the last hour.', 'brand': 'Croq Brew', 'stack': 'beverage stack',
        'promises': ['Drink builder, pour cost, draught yield and every tab reconciled.',
                     'Free-pour drift is invisible until it is 4% of your spirits spend. Iris measures it per bartender, per shift, per bottle.',
                     'Happy hour, weather and the match calendar move demand more than the menu does — so the price and the prep move with them.'],
        'kpis': [('Drinks / hr', '168'), ('Pour variance', '2.1%'), ('Tab recovery', '99.4%')],
        'board': 'The whole bar on one board. Pour cost, draught yield, tab recovery and happy-hour return — live, with Iris naming the shift where the spirits drifted.',
        'story_t': 'Every pour on the record.',
        'story': ['Bars and juice counters leak by the ounce: free pours, syrup drift, age-gate risk, weather nobody planned for. The product is liquid; the losses are too.',
                  'Zentallio meters the flow: drink builders standardise every recipe, compliance is enforced at the till, weather-driven demand shapes prep, and the margin per pour is visible while the shift is still running.'],
        'outcomes': [('+16%', 'margin per pour'), ('100%', 'age-gate compliance'), ('−31%', 'syrup overuse'), ('+19%', 'happy-hour uplift')],
        'groups': [
            G(*CTR, [('Drink Builder', 'Clustering'), ('Fast Bar Workflow', 'Queue ML'), ('Age Verification Gate', 'Rule Engine'), ('Open Tab Management', 'Rule Engine')]),
            G(*CTR2, [('Shisha / Hookah Add-On Module', 'Forecast'), ('Weather-Demand Correlator AI', 'Forecast'), ('Seasonal Drink Menu Auto-Switch', 'Forecast'), ('Loyalty Churn Predictor AI', 'Classifier')]),
            G(*GST, [('Subscription Drink Pass & Loyalty', 'Recommendation'), ('Omni-Channel Ordering', 'Queue ML'), ('Draught Line & Keg Yield Control', 'Anomaly Detection'), ('Cocktail Pour Cost & Recipe Control', 'Cost ML')]),
            G(*PLT, [('Bottle, Wine & Cellar Inventory', 'L1 Zen Rules'), ('Waste, Spillage & Over-Pour Variance', 'Anomaly Detection'), ('Happy Hour & Dynamic Pricing Windows', 'Dynamic Pricing'), ('Responsible Service & Compliance Log', 'L1 Zen Rules'), ('Integration Hub', 'L1 Zen Rules')]),
        ],
    },
    {
        'id': 'health', 'code': 'FB-07', 'num': '07', 'name': 'Health, Wellness & Specialty Diets', 'short': 'Health & Wellness',
        'hue': '#3FD9A4', 'link': '/food/solutions/health-wellness-specialty-diets', 'formats': 8, 'count': 17,
        'headline': 'The AI that runs the bowl, every claim, the plan.', 'brand': 'Croq Verde', 'stack': 'health stack',
        'promises': ['Macros calculated per build, allergens enforced at the till, and every claim on the menu traceable.',
                     'If the menu says 32g of protein, the platform can show which ingredients made it and which batch they came from.',
                     'Subscription meal plans that stay profitable per subscriber, not just popular.'],
        'kpis': [('Bowls / day', '486'), ('Macro accuracy', '99.1%'), ('Allergen incidents', '0')],
        'board': 'Every claim on one board. Macro accuracy, allergen control, subscriber contribution and traceability — live, with Iris naming the claim that can no longer be substantiated.',
        'story_t': 'Trust is the product.',
        'story': ['Health-first customers read every label — and one allergen mistake or broken macro promise ends the relationship. Compliance by spreadsheet cannot keep that promise at scale.',
                  'Zentallio makes trust automatic: farm-to-table traceability on every bowl, labels generated from the actual recipe, subscriptions billed and retained, waste tracked to the ingredient.'],
        'outcomes': [('100%', 'allergen label accuracy'), ('+27%', 'subscription retention'), ('−22%', 'prep waste'), ('4.9★', 'customer trust rating')],
        'groups': [
            G(*GST, [('Build-Your-Own Bowl / Plate Engine', 'Clustering'), ('Subscription Meal Plan Billing', 'Classifier'), ('Meal Plan Subscriptions & Unit Economics', 'Forecast'), ('Loyalty, Goals & Guest Wellness Profile', 'Recommendation')]),
            G(*KIT, [('Omni-Channel Ordering', 'Queue ML'), ('Allergen & Dietary Flag per Item', 'Rule Engine'), ('Calorie & Macro Display per Dish', 'Recommendation'), ('Organic / Batch Inventory Tracking', 'Scoring')]),
            G(*KIT2, [('Nutritional AI Recommender', 'Recommendation'), ('Meal Prep Demand Forecaster AI', 'Forecast'), ('Ingredient Traceability', 'Rule Engine'), ('Macro & Calorie Engine', 'Cost ML')]),
            G(*KITC, [('Allergen Enforcement & Cross-Contact Control', 'L1 Zen Rules'), ('Build-Your-Own Pricing & Portion Logic', 'Dynamic Pricing'), ('Ingredient Sourcing, Batch & Traceability', 'L1 Zen Rules'), ('Nutrition Compliance & Menu Labelling', 'L1 Zen Rules'), ('Integration Hub', 'L1 Zen Rules')]),
        ],
    },
    {
        'id': 'cloud', 'code': 'FB-08', 'num': '08', 'name': 'Cloud Kitchen & Delivery-Only', 'short': 'Cloud Kitchen',
        'hue': '#7B9BFF', 'link': '/food/solutions/cloud-kitchen-delivery-only', 'formats': 7, 'count': 16,
        'headline': 'The AI that runs every brand, the rider gate, the commission.', 'brand': 'Croq Virtual', 'stack': 'cloud stack',
        'promises': ['Six virtual brands out of one kitchen, each with its own P&L and its own aggregator storefronts.',
                     'Prep time, rider ETA and pickup are one sequence. Food that waits on a shelf is the whole margin.',
                     'Aggregator commission decides whether a busy kitchen is a profitable one. Iris prices and routes against it, order by order.'],
        'kpis': [('Orders / hr', '214'), ('Prep to pickup', '3.1m'), ('Brand contribution', '21.4%')],
        'board': 'Every brand on one board. Rider shelf time, commission, brand contribution and platform standing — live, with Iris naming the brand that is busy and unprofitable.',
        'story_t': 'Restaurants made of pure logistics.',
        'story': ['A cloud kitchen is five brands, three aggregators and zero dining room — a business that exists only as order flow. When routing or commission reconciliation slips, no one sees it until the P&L does.',
                  'Zentallio is built for the invisible restaurant: multi-brand routing on one line, surge predicted before it forms, per-brand P&L nightly, and aggregator commissions reconciled to the rupee.'],
        'outcomes': [('+31%', 'orders per kitchen hour'), ('5', 'brands on one line'), ('−19%', 'aggregator commission leakage'), ('12 min', 'average dispatch')],
        'groups': [
            G(*CTR, [('Multi-Brand Order Routing', 'Forecast'), ('Delivery Demand Surge Predictor AI', 'Forecast'), ('Rider Handover & Pickup Gate', 'Queue ML'), ('Dark Store FIFO Inventory', 'Forecast')]),
            G(*KIT, [('Delivery Demand & Prep Forecasting', 'Forecast'), ('Packaging, Cost & Order Assembly', 'Anomaly Detection'), ('Dark Store Inventory & FIFO Depletion', 'L1 Zen Rules'), ('Per-Brand Revenue Settlement', 'Scoring')]),
            G(*PLT, [('Virtual Brand Management', 'Market Gap Model'), ('Delivery Aggregator Sync', 'Forecast'), ('Brand Performance Ranker AI', 'Scoring'), ('Brand-Level P&L & Contribution', 'Cost ML')]),
            G(*PLT2, [('Aggregator Commission & Price Parity', 'Dynamic Pricing'), ('Virtual Brand Launch & Menu Cloning', 'Forecast'), ('Ratings, Refunds & Platform Standing', 'Sentiment ML'), ('Integration Hub', 'L1 Zen Rules')]),
        ],
    },
    {
        'id': 'b2b', 'code': 'FB-09', 'num': '09', 'name': 'Institutional & B2B Food Service', 'short': 'Institutional & B2B',
        'hue': '#8FB3C7', 'link': '/food/solutions/institutional-b2b-food-service', 'formats': 7, 'count': 16,
        'headline': 'The AI that runs the contract, every site, the audit.', 'brand': 'Croq Collective', 'stack': 'B2B stack',
        'promises': ['Headcount billing, subsidy rules, tender compliance and a client invoice that reconciles first time.',
                     'Twelve canteens, four clients, one standard. Cost per meal compared honestly across sites rather than averaged into meaninglessness.',
                     'Nutrition standards, allergen records and food-safety evidence produced on request — because in this sector the audit is not an event, it is the operating condition.'],
        'kpis': [('Meals / day', '14,280'), ('Cost per meal', '$3.42'), ('Invoice accuracy', '99.6%')],
        'board': 'Every site on one board. Cost per meal, participation, compliance and contract margin — live, with Iris naming the site drifting from the model you bid.',
        'story_t': 'Feeding institutions without losing the plot.',
        'story': ['Corporate cafeterias, hospitals, campuses: thousands of meals, subsidy rules, headcount billing, forty sites on forty spreadsheets. Scale here has historically meant blindness.',
                  'Zentallio consolidates it: headcount-accurate billing, voucher and subsidy logic built in, per-site performance on one screen, and a group close that takes days, not weeks.'],
        'outcomes': [('−9%', 'cost per meal served'), ('100%', 'headcount billing accuracy'), ('+15%', 'contract renewals'), ('3 days', 'consolidated close')],
        'groups': [
            G(*CTR, [('Corporate Account Invoicing', 'Anomaly Detection'), ('Event Catering Order Sheet', 'Forecast'), ('Subsidised Meal & Voucher Engine', 'Classifier'), ('No-Show & Headcount Adjuster AI', 'Regression')]),
            G(*KIT, [('Menu Cycles, Nutrition Standards & Compliance', 'L2 Zen Models'), ('Headcount Forecasting & Waste Reduction', 'Forecast'), ('Multi-Site Standards & Central Kitchen Supply', 'Optimisation'), ('Headcount Billing', 'Forecast')]),
            G(*PLT, [('Multi-Location Consolidated Reporting', 'Anomaly Detection'), ('Demand Forecast per Institution AI', 'Forecast'), ('Contract Management & Client Billing', 'L1 Zen Rules'), ('Subsidy, Entitlement & Free Meal Rules', 'L1 Zen Rules')]),
            G(*PLT2, [('Procurement, Tender & Supplier Compliance', 'Forecast'), ('Client Reporting, SLAs & Satisfaction', 'Segmentation'), ('Integration Hub', 'L1 Zen Rules'), ('Food Safety, HACCP & Audit Evidence', 'L1 Zen Rules')]),
        ],
    },
    {
        'id': 'niche', 'code': 'FB-10', 'num': '10', 'name': 'Niche & Experience Concepts', 'short': 'Niche & Experience',
        'hue': '#FF9A62', 'link': '/food/solutions/niche-experience-concepts', 'formats': 7, 'count': 16,
        'headline': 'The AI that runs the experience, the pop-up, every seating.', 'brand': 'Croq Nocturne', 'stack': 'niche stack',
        'promises': ['Ticketed seatings, pop-ups, theme nights and concepts that move.',
                     'A location that exists for six weeks still needs a P&L, a stock count and a way to close the till without internet.',
                     'When the meal is the ticket, no-shows and covers are the same problem — and both are predictable.'],
        'kpis': [('Seatings / week', '42'), ('Ticket yield', '$86.40'), ('No-show', '4.1%')],
        'board': 'Every seating on one board. Ticket yield, run-sheet timing, pop-up payback and no-shows — live, with Iris naming the beat where the room lost the thread.',
        'story_t': 'Concepts that break the clock deserve systems that keep up.',
        'story': ['Brunch-only, 24-hour, pop-up, themed — the most creative formats in F&B usually run on the least suitable software, rebuilt by hand for every launch.',
                  'Zentallio ships the playbook: menus, shifts and billing shaped to the concept, launch in days, and one system that follows the brand from pop-up to permanent.'],
        'outcomes': [('+24%', 'late-night margin'), ('−35%', 'concept launch time'), ('+17%', 'event pre-orders'), ('1', 'system across every pop-up')],
        'groups': [
            G(*CTR, [('Daypart-Only Menu Lockout', 'Forecast'), ('Extended Hours & 24-Hour Shift Close', 'Forecast'), ('Pop-Up Location & Event Tagging', 'Scoring'), ('Theme Night Revenue Analyser AI', 'Attribution')]),
            G(*CTR2, [('Ticketed Seatings & Prepaid Covers', 'Forecast'), ('Experience Design & Run Sheet', 'Optimisation'), ('Theme Nights, Collaborations & Limited Runs', 'Forecast'), ('Merchandise, Retail & Bookable Extras', 'Recommendation')]),
            G(*PLT, [('Mobile, Festival & Multi-Pitch Operations', 'Forecast'), ('Community, Waitlist & Membership', 'Segmentation'), ('Event & Ticket-Based Billing', 'Forecast'), ('Offline Mode', 'Rule Engine')]),
            G(*PLT2, [('Concept Performance Scoring AI', 'Scoring'), ('Pop-Up, Residency & Site P&L', 'Cost ML'), ('Offline-First Trading & Sync', 'L1 Zen Rules'), ('Integration Hub', 'L1 Zen Rules')]),
        ],
    },
]

RULE_TECH = {'L1 Zen Rules', 'Rule Engine'}


def fb_layer(tech):
    if tech in RULE_TECH:
        return 'L1'
    if tech == 'LLM Agent':
        return 'L3'
    return 'L2'


# ---------------------------------------------------------------- Fashion sectors
CORE_POS = ['Checkout', 'Returns & exchange', 'Store credit', 'Tender & reconciliation', 'Tax', 'Discount governance',
            'Customer capture', 'Loyalty', 'Offline resilience', 'Cash management', 'Shift close', 'Audit trail']


def FG(title, sub, layer, items):
    return {'title': title, 'sub': sub, 'layer': layer, 'items': items}


FA = [
    {
        'id': 'apparel', 'code': 'FA-01', 'num': '01', 'name': 'Apparel & Ready-to-Wear', 'short': 'Apparel & RTW', 'hue': '#9B7BFF',
        'count': 6, 'stack': 'apparel stack',
        'does': [('The AI that reads the size curve.', 'A size break caught in week two, not week eight — because the transfer still works while the run is complete.', 'Iris watches every size, in every door, all day.'),
                 ('The AI that times the first markdown.', 'Cut date set per style, per store — going earlier on the right lines beats going deeper on all of them.', 'Iris picks the cut date. You approve it.'),
                 ('The AI that stocks the door that sells.', 'Replenishment routed by what each store actually clears, not by what it ordered last month.', 'Iris moves the stock before you notice it’s stuck.')],
        'kpis': [('Units / hr', '210'), ('Full-price sell-through', '71.4%'), ('Size-run health', '88%')],
        'board': 'Sell-through by style, size-curve health and weeks-of-cover — every door on one board.',
        'company': 'Lumière Mode · 180 stores · Europe', 'alert': 'Style AW-4412 breaking on M / L in 6 stores.',
        'l1': [('Gross margin · season-to-date', '≥ 48%', '52.4%'), ('Repeat purchase rate', '≥ 35%', '38%'), ('Full-price sell-through', '≥ 67%', '71.4%'), ('Demand forecast accuracy', '≥ 89%', '92.8%')],
        'l2': [('Size-curve drift', 'break risk by size', '93.4%'), ('Sell-through', '8-week curve by style', '91.8%'), ('Markdown timing', 'first-cut date', '90.2%')],
        'l3': [('What just moved?', 'Size break detected on 2 sizes, 6 doors — rule fired at 09:14.'), ('Why, and what do I do?', 'Move 84 units from the three slowest doors — holds full price 11 more days.')],
        'groups': [FG('On the floor', 'Where stock sits, moves and sells.', 'L1', [('Allocation & replenishment rules', 'Routing'), ('Core vs fashion mix control', 'Distribution')]),
                   FG('Planning & margin', 'What is modelled before it lands.', 'L2', [('Size-curve break detection', 'Signal grid'), ('Style sell-through forecast', 'Model trace'), ('Markdown timing engine', 'Distribution'), ('Fitting-room conversion', 'Distribution')])],
        'scen': [('Allocation & replenishment rules', 'L1', 'Tonight’s run proposes 142 moves (1,880 units across 22 doors); 86% of past runs accepted; 1 move held. Rules: min cover per door 2.0 weeks, run integrity at sender, max 8 moves per door per night, transfer cost ceiling $2.50/unit.', 'The run is weighted by conversion, not depth — Lille holds the units but Paris sells M and L twice as fast. One move is held back because it would open an S gap at Rennes to close an M gap at Bordeaux; that trade is not worth making.'),
                 ('Size-curve break detection', 'L2', '6 of 22 doors breaking on M and L; 84 units to move from 3 slow doors; 11 days full-price runway if moved today; 4.2 pts margin at risk if marked down instead.', 'The break concentrates in the four doors that took the first allocation and were never topped up — that says allocation, not demand. Moving 84 units from the three slowest doors holds full price 11 more days; markdown instead costs 4.2 points.')],
    },
    {
        'id': 'bridal', 'code': 'FA-02', 'num': '02', 'name': 'Ethnic, Bridal & Couture', 'short': 'Ethnic & Bridal', 'hue': '#E879C7',
        'count': 7, 'stack': 'couture stack',
        'does': [('The AI that holds the promise date.', 'Every open order scored against real atelier capacity — so a slip surfaces while it’s still recoverable, not at the fitting.', 'Iris knows which promise is about to break.'),
                 ('The AI that plans the karigar’s week.', 'Work loaded by skill and stage — embellishment, cutting, finishing — so capacity is a number rather than a hope.', 'Iris loads the atelier by skill, not by hope.'),
                 ('The AI that keeps every measurement.', 'Each alteration writes back to the customer’s file, so the second order fits better than the first.', 'Iris remembers a fit you took two years ago.')],
        'kpis': [('Open orders', '214'), ('On-time handover', '96.1%'), ('Atelier load', '84%')],
        'board': 'Order-book value, atelier load, promise-date risk and deposit exposure in one view.',
        'company': 'Maison Zara · 46 ateliers · Pakistan & Gulf', 'alert': 'Week 34 · 4 bridal orders on the same two karigars.',
        'l1': [('Open order-book value', '≥ 3.9M', '3.9M'), ('Returning bridal clients', '≥ 60%', '64%'), ('On-time handover', '≥ 92%', '96.1%'), ('Promise-date accuracy', '≥ 87%', '91.4%')],
        'l2': [('Promise-date risk', 'slip probability by order', '92.1%'), ('Atelier load', 'stage capacity', '89.6%'), ('Drop sizing', 'per-city run size', '90.7%')],
        'l3': [('What just moved?', 'Capacity rule breached — embellishment stage over-committed by 38 hours.'), ('Why, and what do I do?', 'Move embellishment on two orders now — every promise date holds.')],
        'groups': [FG('In the atelier', 'Every open order, stage by stage.', 'L1', [('Measurement & fit profile', 'Distribution'), ('Appointment & consultation studio', 'Live queue'), ('Deposit, instalment & cancellation control', 'Contribution')]),
                   FG('The order book', 'What the book says before the fitting.', 'L2', [('Promise-date risk scoring', 'Detection'), ('Atelier & karigar capacity planning', 'Capacity'), ('Unstitched & lawn drop planning', 'Routing'), ('Ask Iris · order book', 'Live queue')])],
        'scen': [('Measurement & fit profile', 'L1', '1,840 versioned client profiles; 2.1 alterations per order (−0.4 vs last year); 64% fit first time (+9 pts); 3 files stale >24 months. Each alteration round costs ~6 atelier hours.', 'A client’s file at v4 carries shoulder and fall adjustments from 2023. Applying it to the new order removes an expected fitting round — six atelier hours in a week when zardozi is already over-committed.'),
                 ('Promise-date risk scoring', 'L2', '4 orders at risk in week 34; highest slip probability 0.72; zardozi stage committed 118 of 80 available hours (over by 38).', 'All four at-risk orders route through one stage and one pair of hands — zardozi. This is not four problems, it is one. Moving the embellishment on two orders to the contract karigar clears the stage and every promise date holds.')],
    },
    {
        'id': 'kids', 'code': 'FA-03', 'num': '03', 'name': 'Kidswear & Teen', 'short': 'Kidswear & Teen', 'hue': '#FFB86B',
        'count': 6, 'stack': 'kidswear stack',
        'does': [('The AI that beats the school bell.', 'Uniform size packs planned against the intake calendar, weeks before the queue forms at the counter.', 'Iris counts down to intake week for you.'),
                 ('The AI that knows when they outgrow you.', 'The size-up moment predicted per family, and the offer timed to land before they shop somewhere else.', 'Iris spots the size-up before the family does.'),
                 ('The AI that plans the gifting spike.', 'Eid, birthdays and holidays modelled as the lumpy demand they actually are, not smoothed into an average.', 'Iris sees the spike before the calendar does.')],
        'kpis': [('Baskets / hr', '96'), ('Season readiness', '92.4%'), ('Repeat families', '47%')],
        'board': 'Age-band sell-through, school-season readiness and repeat-family rate.',
        'company': 'Petit Nord · 74 stores · school season', 'alert': '3 schools · uniform packs 19 days behind last year.',
        'l1': [('Gross margin · season-block', '≥ 42%', '44.8%'), ('Repeat families', '≥ 44%', '47%'), ('School-season readiness', '≥ 88%', '92.4%'), ('Age-band forecast accuracy', '≥ 87%', '90.6%')],
        'l2': [('Age-band demand', 'units by band', '90.9%'), ('Season readiness', 'pack fill by school', '92.3%'), ('Growth cycle', 'size-up timing', '88.4%')],
        'l3': [('What just moved?', 'Readiness rule fired — pack fill below 90% with 5 weeks to intake.'), ('Why, and what do I do?', 'Pull the reorder forward now — clears intake week without airfreight.')],
        'groups': [FG('At the counter', 'Lists, packs and families in front of you.', 'L1', [('School-season readiness', 'Coverage'), ('Safety & compliance traceability', 'Coverage'), ('Maternity-to-newborn journey', 'Routing')]),
                   FG('The season ahead', 'What the calendar is about to do.', 'L2', [('Age-band demand forecast', 'Model trace'), ('Growth-cycle repeat prediction', 'Model trace'), ('Gifting & occasion spike planning', 'Capacity')])],
        'scen': [('School-season readiness', 'L1', 'Season readiness 92.4% vs 98% target; 3 schools 19 days behind last year; 5 weeks to a fixed intake date; intake week alone is 46% of the season.', 'Two schools are three weeks behind on a date that cannot move. There is no recovery window after intake week — last year the same gap cost 14% of intake footfall to queue walkouts. Pull both reorders forward now and it clears without airfreight.'),
                 ('Age-band demand forecast', 'L2', 'Model accuracy 90.6% by band; age 9–10 is −8% vs plan while 11–14 over-sells by +16%; 4,600 families moved up a band.', 'Age 9–10 is not losing customers, it is losing them upward — the two variances are the same children. Rebalancing the buy between the bands fixes both numbers at once.')],
    },
    {
        'id': 'sports', 'code': 'FA-04', 'num': '04', 'name': 'Sportswear & Activewear', 'short': 'Sportswear', 'hue': '#5CE1A6',
        'count': 6, 'stack': 'sportswear stack',
        'does': [('The AI that clears the drop.', 'Allocation by conversion, not store rank — so a limited release sells out where it was always going to sell.', 'Iris knows which doors sell out and which sit.'),
                 ('The AI that sizes the release.', 'Pre-registration, traffic and prior drops turned into a buy quantity before the launch window opens.', 'Iris reads the queue before it forms.'),
                 ('The AI that reconciles the rebate.', 'Sell-through claims and co-op spend checked against contract terms — automatically, every cycle.', 'Iris reads the contract so nobody else has to.')],
        'kpis': [('Drop sell-out', '89.3%'), ('Full-price ratio', '82%'), ('Member mix', '61%')],
        'board': 'Drop sell-out rate, brand-partner sell-through and full-price ratio.',
        'company': 'Kinetic · 92 doors · drop season', 'alert': 'Friday drop · over-allocated to 2 flagship doors.',
        'l1': [('Gross margin · drop season', '≥ 43%', '46.2%'), ('Member mix of sales', '≥ 57%', '61%'), ('Drop sell-out rate', '≥ 85%', '89.3%'), ('Release demand accuracy', '≥ 89%', '93.1%')],
        'l2': [('Release demand', 'drop sell-out', '93.6%'), ('Allocation fit', 'conversion by door', '92.0%'), ('Re-order cycle', 'replacement timing', '89.8%')],
        'l3': [('What just moved?', 'Allocation rule flagged — two doors hold 41% of units on 18% of conversion.'), ('Why, and what do I do?', 'Reallocate 140 pairs — clears the drop inside 48 hours.')],
        'groups': [FG('The launch', 'What is releasing, and where it clears.', 'L1', [('Technical size & fit guidance', 'Signal grid'), ('Team & club bulk orders', 'Live queue'), ('Brand-partner rebate reconciliation', 'Signal grid')]),
                   FG('The season', 'What the buy should have been.', 'L2', [('Drop & launch allocation', 'Routing'), ('Limited-release demand modelling', 'Model trace'), ('Training-cycle re-order prediction', 'Model trace')])],
        'scen': [('Technical size & fit guidance', 'L1', 'Return rate 16.8% vs 14% target; 58% of returns cite fit; guided silhouettes return at 10.1% vs 24.6% un-guided; compression base layer (31% returns) has no guidance.', 'The evidence is already in your own data — guidance halves the return rate where it exists. Compression is the worst line and has no guidance at all. This is two silhouettes missing a rule, not a modelling problem.'),
                 ('Drop & launch allocation', 'L2', 'Projected sell-out 89.3% (+11 pts); 140 pairs to move from 2 flagship doors; 48-hour clearance window across 92 doors.', 'The drop is allocated by store size, not by who buys this product. Two flagships hold 41% of units on 18% of conversion while streetwear doors clear everything in hours. Moving 140 pairs lifts sell-out to 89% inside 48 hours.')],
    },
    {
        'id': 'footwear', 'code': 'FA-05', 'num': '05', 'name': 'Footwear', 'short': 'Footwear', 'hue': '#7FA8FF',
        'count': 6, 'stack': 'footwear stack',
        'does': [('The AI that finds the missing size.', 'A run with a hole in it is a lost sale you never see. This is the one that sees it — and fills it first.', 'Iris finds the gap the day it opens.'),
                 ('The AI that pairs the second item.', 'What actually sells together — bag with the shoe, belt with the formal — prompted while the customer is still at the till.', 'Iris knows what sells with what.'),
                 ('The AI that walks the whole run.', 'Every article, every size, every door — counted nightly so the gap shows up before the customer does.', 'Iris checks the run so nobody has to.')],
        'kpis': [('Pairs / hr', '132'), ('Size-run complete', '91.8%'), ('Attach rate', '34%')],
        'board': 'Size-run completeness, pairs per hour and full-price sell-through by door.',
        'company': 'Stride · 118 doors · full estate', 'alert': '9 articles missing their two best-selling sizes.',
        'l1': [('Gross margin', '≥ 46%', '48.6%'), ('Attach rate', '≥ 31%', '34%'), ('Size-run completeness', '≥ 88%', '91.8%'), ('Article forecast accuracy', '≥ 88%', '92.2%')],
        'l2': [('Run integrity', 'hole risk by article', '92.7%'), ('Attach propensity', 'pair-with likelihood', '90.4%'), ('Article curve', '8-week sell-through', '91.1%')],
        'l3': [('What just moved?', 'Run-integrity rule fired on 9 articles across 23 doors.'), ('Why, and what do I do?', 'Fill those runs first — worth more than the new intake.')],
        'groups': [FG('On the wall', 'Every run, every box, every door.', 'L1', [('Size-run integrity', 'Signal grid'), ('Single-pair transfer engine', 'Routing'), ('Box, shelf & stockroom locator', 'Distribution')]),
                   FG('Behind the wall', 'What the numbers say to buy next.', 'L2', [('Article sell-through forecast', 'Model trace'), ('Fit & return-reason learning', 'Distribution'), ('Release & resale-pressure demand', 'Model trace')])],
        'scen': [('Size-run integrity', 'L1', '9 articles broken on UK 8 and 9 across 23 doors; runs 91.8% complete vs 96% target; UK 8 + 9 are 46% of all pairs sold; £38k weekly sale at risk.', 'The run looks 92% complete because the count is dominated by sizes nobody buys. Filling these nine runs first is worth more than this week’s entire new-arrival intake — and the KPI should be re-weighted by demand.'),
                 ('Article sell-through forecast', 'L2', '8-week projection 68.2% (±2.8 pts); model accuracy 92.2%; −6.4% vs buy plan; formal & dress projects 44% while every other category is at or ahead of plan.', 'The shortfall is one category, not one article — office footfall has not returned to these doors. Cutting the formal balance and moving it into boot, which is running ahead, lands the season on plan.')],
    },
    {
        'id': 'beauty', 'code': 'FA-06', 'num': '06', 'name': 'Cosmetics & Beauty', 'short': 'Cosmetics & Beauty', 'hue': '#FF7BAC',
        'count': 6, 'stack': 'beauty stack',
        'does': [('The AI that watches the expiry date.', 'Batch and shelf life tracked per line, so nothing sells past its date and nothing sits past its margin.', 'Iris clears it before it expires, not after.'),
                 ('The AI that reads the shade curve.', 'Which shades break first, by store and by season — because a foundation range sells like a size curve, not like a product.', 'Iris knows which shade goes first, and where.'),
                 ('The AI that times the refill.', 'When a customer actually runs out, and the prompt timed to land a week before rather than a month after.', 'Iris knows when the bottle runs out.')],
        'kpis': [('Baskets / hr', '124'), ('Repeat purchase', '58%'), ('Expiry write-off', '0.9%')],
        'board': 'Repeat-purchase rate, shade availability, expiry exposure and counter productivity on one board.',
        'company': 'Éclat Beauty · 63 counters · Europe', 'alert': '2 skincare batches expire in 38 days, in the 3 slowest doors.',
        'l1': [('Gross margin', '≥ 53%', '57.1%'), ('Repeat purchase rate', '≥ 54%', '58%'), ('Shade availability', '≥ 90%', '94.2%'), ('Replenishment accuracy', '≥ 88%', '91.8%')],
        'l2': [('Shade curve', 'break order by shade', '92.5%'), ('Refill timing', 'days to run-out', '91.3%'), ('Expiry risk', 'cover vs shelf life', '93.0%')],
        'l3': [('What just moved?', 'Expiry rule fired — 38 days of cover left, 91 days of stock on hand.'), ('Why, and what do I do?', 'Move them now — clears at full price instead of a write-off.')],
        'groups': [FG('At the counter', 'Shades, testers and the customer in front of you.', 'L1', [('Batch, expiry & shelf-life control', 'Distribution'), ('Tester & sampling consumption', 'Distribution'), ('Counter & concession settlement', 'Contribution'), ('Ingredient & recall traceability', 'Coverage')]),
                   FG('Behind the counter', 'Batches, expiry and what it costs.', 'L2', [('Shade-curve demand', 'Signal grid'), ('Replenishment cycle prediction', 'Model trace')])],
        'scen': [('Batch, expiry & shelf-life control', 'L1', 'Shortest cover left 38 days on 2 batches; expiry write-off 0.9% vs 2.4% last year; £46k of stock inside 90 days across 63 counters.', 'Two batches have 38 days of life against 91 days of stock, and they sit in the three slowest counters. Moved to the counters that turn skincare twice as fast, both clear at full price instead of becoming a write-off.'),
                 ('Shade-curve demand', 'L2', 'Shade availability 94.2% vs 97% target; 6 deep shades broken; fastest shade sells 3.1×; only 31 of 63 counters carry the full deep range.', 'The deep range is not under-selling, it is under-distributed — where it is stocked it hits plan. One deep shade is out in 14 counters while a light shade sits on 9.8 weeks of cover. That is an allocation decision made on the wrong data.')],
    },
    {
        'id': 'textile', 'code': 'FA-07', 'num': '07', 'name': 'Fabric & Textile', 'short': 'Fabric & Textile', 'hue': '#C9A27C',
        'count': 6, 'stack': 'textile stack',
        'does': [('The AI that counts the metre.', 'Cut wastage tracked per table, per branch, per roll — because in this business the yield is the margin.', 'Iris logs the wastage nobody writes down.'),
                 ('The AI that matches the dye lot.', 'Shade continuity guaranteed across a cut — the complaint that ends a customer relationship, prevented.', 'Iris catches a shade drift mid-roll.'),
                 ('The AI that sizes the next run.', 'Each design run and colourway planned against last season’s actual sell-through, not against the buyer’s memory of it.', 'Iris sizes the run from what actually sold.')],
        'kpis': [('Metres / day', '1,840'), ('Cut yield', '96.4%'), ('Roll ageing', '21 days')],
        'board': 'Metre-level sell-through, cut wastage and roll ageing — by branch and by cutting table.',
        'company': 'Loom & Lot · 38 branches', 'alert': 'Premium suiting · wastage 4.1% above counter average.',
        'l1': [('Gross margin', '≥ 39%', '41.7%'), ('Repeat trade buyers', '≥ 40%', '43%'), ('Cut yield', '≥ 92%', '96.4%'), ('Run-size forecast accuracy', '≥ 86%', '90.2%')],
        'l2': [('Cut yield', 'wastage by table', '91.6%'), ('Run sizing', 'metres by colourway', '89.9%'), ('Lot ageing', 'clearance risk', '90.5%')],
        'l3': [('What just moved?', 'Yield rule fired — one branch, one cutting table, started 9 days ago.'), ('Why, and what do I do?', 'Re-brief that table — recovers the yield inside a fortnight.')],
        'groups': [FG('At the cut counter', 'Rolls, cuts and remnants as they happen.', 'L1', [('Roll, lot & dye-batch traceability', 'Coverage'), ('Cutting-table productivity', 'Distribution'), ('Mill-to-outlet clearance routing', 'Routing')]),
                   FG('Across the branches', 'Runs, lots and where they should go.', 'L2', [('Cut-length yield & remnant recovery', 'Capacity'), ('Design-run & colourway planning', 'Signal grid'), ('Seasonal & festive drop planning', 'Routing')])],
        'scen': [('Roll, lot & dye-batch traceability', 'L1', 'Trace time 0.8s roll to dye lot; 1,240 live rolls across 38 branches, 100% scanned on receipt; 3 cuts today split a lot; tolerance ΔE 1.5 (suiting lots measured at ΔE 3.1).', 'Two cuts span lots with shade drift above tolerance — a suiting order at ΔE 3.1 will show as two different fabrics once made up. The customer will not see it in the shop; they will see it at the first fitting, and by then the cloth is cut. Hold the cuts and source a single lot.'),
                 ('Cut-length yield & remnant recovery', 'L2', 'Cut yield 96.4% vs 97.5% target; wastage 3.6%; £8,400 recoverable remnant value; one branch loses 11.4% on cuts under 2 metres.', 'The branch is not careless across the board — it loses yield only on short cuts. One table, one habit, one cut length. A minimum-cut rule and priced offcuts recover most of the loss without retraining anyone.')],
    },
    {
        'id': 'home', 'code': 'FA-08', 'num': '08', 'name': 'Home Textiles & Furnishing', 'short': 'Home Textiles', 'hue': '#8FB3C7',
        'count': 6, 'stack': 'home-textiles stack',
        'does': [('The AI that measures the window.', 'Measure visit, making, delivery and installation on one promise date — so a curtain order stops living in somebody’s notebook.', 'Iris holds the fitting date to the day.'),
                 ('The AI that completes the room.', 'Sheet with the duvet, cushion with the throw — the pieces that finish a set, prompted before the customer reaches the door.', 'Iris knows what finishes the set.'),
                 ('The AI that matches the shade.', 'One room, one dye lot, across every piece in the set — the mismatch that turns a delivery into a return, caught at picking.', 'Iris keeps the shade true across the set.')],
        'kpis': [('Orders / week', '96'), ('On-time install', '93.8%'), ('Set attach', '37%')],
        'board': 'Made-to-measure pipeline health, on-time installation, set attach rate and room-set sell-through.',
        'company': 'Maison Linen · 52 showrooms', 'alert': 'Next week · 14 made-to-measure orders on 2 installers.',
        'l1': [('Gross margin', '≥ 42%', '45.3%'), ('Room-set attach rate', '≥ 34%', '37%'), ('On-time installation', '≥ 90%', '93.8%'), ('Made-to-measure accuracy', '≥ 86%', '89.7%')],
        'l2': [('Fitter capacity', 'install slippage', '90.1%'), ('Set attach', 'completion likelihood', '88.7%'), ('Spec demand', 'GSM & size mix', '91.4%')],
        'l3': [('What just moved?', 'Capacity rule fired — two orders promised the same day, same fitter.'), ('Why, and what do I do?', 'Move one to Thursday — both promise dates hold.')],
        'groups': [FG('In the showroom', 'Orders, sets and the promise date.', 'L1', [('Made-to-measure pipeline', 'Routing'), ('Fitting & installation scheduling', 'Capacity'), ('Dye-lot & shade continuity', 'Distribution')]),
                   FG('On the road', 'Measure, make and install.', 'L2', [('Room-set & collection attach', 'Distribution'), ('Size, GSM & thread-count demand', 'Signal grid'), ('Wedding & seasonal peak planning', 'Capacity')])],
        'scen': [('Made-to-measure pipeline', 'L1', '68 orders in pipeline; on-time install 93.8% vs 96% target; 2 orders promised the same day to the same fitter; 19 days measure to install; Friday booked 16 of 8 hours while Thursday has 3 free.', 'The diary accepted both orders because it books by day, not by hours. Moving the single-room curtain to Thursday keeps both promise dates — and the diary should switch to hours.'),
                 ('Room-set & collection attach', 'L2', 'Set attach 37% (+3 pts); 2.4 pieces per basket; £64 uplift when a set is completed; 82% of attaches happen in the same basket; rug underlay attaches at only 18%.', 'An attach not made at the till is usually never made. Rug underlay is not optional, yet no prompt was ever written for it — add the underlay prompt and bundle it at point of sale.')],
    },
    {
        'id': 'market', 'code': 'FA-09', 'num': '09', 'name': 'Marketplace & Online Selling', 'short': 'Marketplace & Online', 'hue': '#15F2F2',
        'count': 6, 'stack': 'marketplace stack',
        'does': [('The AI that holds one stock pool.', 'Web, floor and every marketplace reading the same availability — so the oversell that costs you the account never happens.', 'Iris keeps every channel honest about stock.'),
                 ('The AI that costs the real margin.', 'Commission, shipping, returns and ad spend charged to the order that caused them, not smoothed across the month.', 'Iris tells you which channel actually pays.'),
                 ('The AI that spots the dead listing.', 'Which listings convert and which have quietly stopped — surfaced before a season’s stock is buried behind them.', 'Iris finds the listing that stopped selling.')],
        'kpis': [('Channels live', '9'), ('Order accuracy', '99.1%'), ('Return rate', '18%')],
        'board': 'Channel margin after fees, order accuracy, return rate and SLA performance side by side.',
        'company': 'Nine channels · one stock pool', 'alert': 'One channel · best on revenue, worst on margin.',
        'l1': [('Margin after channel fees', '≥ 28%', '31.4%'), ('Repeat buyer rate', '≥ 26%', '29%'), ('Order accuracy', '≥ 95%', '99.1%'), ('Channel demand accuracy', '≥ 89%', '93.4%')],
        'l2': [('Channel margin', 'contribution after fees', '93.2%'), ('Return risk', 'abuse likelihood', '90.8%'), ('Listing health', 'conversion decay', '92.6%')],
        'l3': [('What just moved?', 'Fee rule fired — 14% commission against a 31% gross on this channel.'), ('Why, and what do I do?', 'Cut ad spend here and reprice — or the volume is costing you.')],
        'groups': [FG('Across the channels', 'Orders, stock and SLA on every channel.', 'L1', [('Single stock pool across channels', 'Distribution'), ('Order routing & SLA control', 'Routing')]),
                   FG('What it actually earns', 'Fees, returns and the real margin.', 'L2', [('Channel margin after fees', 'Contribution'), ('Listing & content health', 'Coverage'), ('Return & refund abuse detection', 'Detection'), ('Price parity & buy-box monitoring', 'Coverage')])],
        'scen': [('Single stock pool across channels', 'L1', '0 oversells this period across 9 channels; pool reconciles 1.4s after each sale; before the single pool: 34 oversells and 3 account warnings in 12 months; one marketplace showing 46 units behind the pool.', 'The 46-unit gap is a manual safety buffer someone set and never removed. It is not an oversell risk — it is 46 units you are refusing to sell on your largest channel. Remove the buffer and audit all channels.'),
                 ('Channel margin after fees', 'L2', 'Margin after fees 31.4% vs 46% gross; one channel negative; ad spend 6.2% of revenue; on the weakest channel every £100 of gross loses £14 commission, £22 returns and £11 ads.', 'The biggest marketplace is the best channel on revenue and the only negative one on contribution — and returns, not commission, do the damage. Fix the return reasons, cut ad spend there and reprice, or the volume is costing money.')],
    },
]

TECH_TAGS = {
    'Anomaly Detection': 'Flags unusual variance — shrink, leakage, abuse or drift.',
    'Attribution': 'Assigns revenue or outcome to the cause that produced it.',
    'Capacity': 'Plans work against real capacity (atelier, fitters, peaks).',
    'Classifier': 'Predicts a category or outcome (e.g. no-show, churn, eligibility).',
    'Clustering': 'Groups similar items, builds or customers to standardise and price them.',
    'Contribution': 'Shows true contribution after fees, deposits or settlements.',
    'Cost ML': 'Models true cost and margin at recipe, item or brand level.',
    'Coverage': 'Checks that every item, school, lot or listing is covered to standard.',
    'Detection': 'Detects risk early (slip, abuse).',
    'Distribution': 'Shows how stock, demand or outcomes are spread, to rebalance them.',
    'Dynamic Pricing': 'Moves price by time, stock, shelf life or channel.',
    'Forecast': 'Predicts demand, volume or timing ahead of the event.',
    'IoT': 'Reads sensors and machines (temperature, freezers, equipment).',
    'L1 Zen Rules': 'A deterministic business rule (threshold, gate or policy) that fires instantly.',
    'L2 Zen Models': 'A forecasting / ML model layer.',
    'LLM Agent': 'An AI agent that converses and acts (e.g. social selling).',
    'Live queue': 'A live list of work to act on now.',
    'Market Gap Model': 'Finds unmet demand to shape a new virtual brand.',
    'Memory': 'Recalls an individual customer’s favourites or history.',
    'Model trace': 'A forecast shown with its trace, so you see why it predicts what it does.',
    'Optimisation': 'Finds the best plan under constraints (run sheet, central kitchen supply).',
    'Queue ML': 'Models that sequence and time queues, stations or channels.',
    'Recommendation': 'Suggests the next item, offer or pairing for a guest or customer.',
    'Regression': 'Predicts a continuous value (e.g. turn time, headcount).',
    'Routing': 'Decides where stock, orders or work should go.',
    'Rule Engine': 'Deterministic rule logic (e.g. age gate, split bill, tab rules).',
    'Scoring': 'Ranks or scores items, staff, brands or concepts.',
    'Segmentation': 'Groups customers, sites or staff by behaviour.',
    'Segmentation ML': 'Groups customers by behaviour (e.g. RFM).',
    'Sentiment ML': 'Reads feedback, reviews and ratings for tone and cause.',
    'Signal grid': 'A live grid of signals by item, size or door that shows breaks as they open.',
}
